language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t brentfortman/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true brentfortman/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-629758010476"
  bucket_path: "docker-react"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
