language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t brentfortman/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true brentfortman/docker-react npm run test -- --coverage
